use bdbilheteria;

insert into timefutebol (nomeTime, cnpjTime) values ('ABC FC', '001');
insert into timefutebol (nomeTime, cnpjTime) values ('Corinthians', '002');
insert into timefutebol (nomeTime, cnpjTime) values ('São Paulo', '003');
insert into timefutebol (nomeTime, cnpjTime) values ('Palmeiras', '004');
insert into timefutebol (nomeTime, cnpjTime) values ('Santos FC', '005');
insert into timefutebol (nomeTime, cnpjTime) values ('América Futebol Clube/RN', '006');
insert into timefutebol (nomeTime, cnpjTime) values ('América Futebol Clube/MG', '007');
insert into timefutebol (nomeTime, cnpjTime) values ('Santa Cruz/RN', '008');
insert into timefutebol (nomeTime, cnpjTime) values ('Criciúma/SC', '009');
insert into timefutebol (nomeTime, cnpjTime) values ('Palmeira/RN', '010');
insert into timefutebol (nomeTime, cnpjTime) values ('Potiguar de Mossoró', '011');
insert into timefutebol (nomeTime, cnpjTime) values ('Baraúnas/RN', '012');
insert into timefutebol (nomeTime, cnpjTime) values ('Portuguesa/SP', '013');
insert into timefutebol (nomeTime, cnpjTime) values ('Fortaleza/CE', '014');
insert into timefutebol (nomeTime, cnpjTime) values ('Globo/RN', '015');
insert into timefutebol (nomeTime, cnpjTime) values ('Ceará/CE', '016');
insert into timefutebol (nomeTime, cnpjTime) values ('Figueirense/SC', '017');
insert into timefutebol (nomeTime, cnpjTime) values ('CRB/AL', '018');
insert into timefutebol (nomeTime, cnpjTime) values ('Atlético/GO', '019');
insert into timefutebol (nomeTime, cnpjTime) values ('Goiás/GO', '020');
insert into timefutebol (nomeTime, cnpjTime) values ('Vila Nova/GO', '021');
insert into timefutebol (nomeTime, cnpjTime) values ('Nacional/MA', '022');
insert into timefutebol (nomeTime, cnpjTime) values ('Cuiabá/MT', '023');
insert into timefutebol (nomeTime, cnpjTime) values ('Figueirense/SC', '024');
insert into timefutebol (nomeTime, cnpjTime) values ('Coritiba/PR', '025');
insert into timefutebol (nomeTime, cnpjTime) values ('Clube Atlético/PR', '026');
insert into timefutebol (nomeTime, cnpjTime) values ('Paraná/PR', '027');
insert into timefutebol (nomeTime, cnpjTime) values ('Grêmio/RS', '028');
insert into timefutebol (nomeTime, cnpjTime) values ('Internacional/RS', '029');
insert into timefutebol (nomeTime, cnpjTime) values ('Juventude/RS', '030');
insert into timefutebol (nomeTime, cnpjTime) values ('Caxias/RS', '031');
insert into timefutebol (nomeTime, cnpjTime) values ('Sampaio Correa/MA', '032');
insert into timefutebol (nomeTime, cnpjTime) values ('ASA/AL', '033');
insert into timefutebol (nomeTime, cnpjTime) values ('CSA/AL', '034');
insert into timefutebol (nomeTime, cnpjTime) values ('Vitória/BA', '035');
insert into timefutebol (nomeTime, cnpjTime) values ('Bahia/BA', '036');
insert into timefutebol (nomeTime, cnpjTime) values ('Bahia de Feida/BA', '037');
insert into timefutebol (nomeTime, cnpjTime) values ('Flamengo/RJ', '038');
insert into timefutebol (nomeTime, cnpjTime) values ('Vasco da Gama/RJ', '039');
insert into timefutebol (nomeTime, cnpjTime) values ('Fluminense/RJ', '040');
insert into timefutebol (nomeTime, cnpjTime) values ('Botafogo/RJ', '041');
insert into timefutebol (nomeTime, cnpjTime) values ('Treze/PB', '043');
insert into timefutebol (nomeTime, cnpjTime) values ('Campinense/PB', '044');
insert into timefutebol (nomeTime, cnpjTime) values ('Botafogo/PB', '045');
insert into timefutebol (nomeTime, cnpjTime) values ('CSP/PB', '042');
insert into timefutebol (nomeTime, cnpjTime) values ('Icasa/CE', '046');
insert into timefutebol (nomeTime, cnpjTime) values ('São Caetano/SP', '047');
insert into timefutebol (nomeTime, cnpjTime) values ('Ponte Preta/SP', '048');
insert into timefutebol (nomeTime, cnpjTime) values ('Guarani/SP', '049');
insert into timefutebol (nomeTime, cnpjTime) values ('Bragantino/SP', '050');

update timefutebol set anofundacao='1900';

